
service: doc-uploader

package:
    individually: true

provider:
    name: aws
    region: us-east-2
    runtime: provided
    architecture: x86_64
    memorySize: 512
    timeout: 10
    lambdaHashingVersion: 20201221
    versionFunctions: false
    logs:
        httpApi: true

functions:
    http-endpoint:
        handler: doc-uploader
        events:
            - httpApi: '*'
        package:
            artifact: .lambda/doc-uploader/doc-uploader.zip
