
service: doc-uploader

package:
    individually: true

provider:
    name: aws
    region: us-east-2
    runtime: provided
    architecture: x86_64
    memorySize: 512
    timeout: 10
    lambdaHashingVersion: 20201221
    versionFunctions: false

functions:
    doc-upload:
        handler: doc-uploader
        ephemeralStorageSize: 2048
        events:
            - s3:
                bucket: spi-dev-docs-inbox
                event: s3:ObjectCreated:*
                rules:
                    - suffix: .zip
                existing: true
                forceDeploy: true
        package:
            artifact: .lambda/doc-uploader/doc-uploader.zip
