AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Arch:
    Type: String
    Default: x86_64
    AllowedValues:
      - arm64
      - x86_64

  Env:
    Type: String
    AllowedValues:
      - test
      - prod

Mappings:
  EnvMapping:
    test:
      Arch: arm64
      InboxBucket: spi-scratch-inbox
      # We need to specify two output buckets in prod, so we hack around this by specifying scratch
      # twice here.
      OutputBucket1: spi-scratch
      OutputBucket2: spi-scratch
    prod:
      Arch: x86_64
      InboxBucket: spi-docs-inbox
      OutputBucket1: spi-dev-docs
      OutputBucket2: spi-prod-docs


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - !FindInMap [ EnvMapping, !Ref Env, Arch ]
      CodeUri: ./.lambda/doc-uploader/lambda.zip
      Handler: "haha"
      Runtime: provided.al2
      MemorySize: 2048
      EphemeralStorage:
        Size: 2048
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
                - s3:DeleteObject
              Resource: !Sub
                - 'arn:aws:s3:::${Bucket}/*'
                - Bucket: !FindInMap [ EnvMapping, !Ref Env, InboxBucket ]
            - Effect: Allow
              Action:
                - s3:*
              Resource:
                - !Sub
                  - 'arn:aws:s3:::${Bucket}/*'
                  - Bucket: !FindInMap [ EnvMapping, !Ref Env, OutputBucket1 ]
                - !Sub
                  - 'arn:aws:s3:::${Bucket}'
                  - Bucket: !FindInMap [ EnvMapping, !Ref Env, OutputBucket1 ]
                - !Sub
                  - 'arn:aws:s3:::${Bucket}/*'
                  - Bucket: !FindInMap [ EnvMapping, !Ref Env, OutputBucket2 ]
                - !Sub
                  - 'arn:aws:s3:::${Bucket}'
                  - Bucket: !FindInMap [ EnvMapping, !Ref Env, OutputBucket2 ]

      Environment:
        Variables:
          LOG_LEVEL: info
      Events:
        InboxEvent:
          Type: S3
          Properties:
            Bucket: !Ref InboxBucketResource
            Events: s3:ObjectCreated:*

  InboxBucketResource:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !FindInMap [ EnvMapping, !Ref Env, InboxBucket ]
      LifecycleConfiguration:
        Rules:
          - Id: InboxExpirationRule
            Status: Enabled
            ExpirationInDays: 1
  
  # explicitly create log group to ensure logs are only preserved 14 days (otherways always)
  UploadFunctionLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UploadFunction}"
      RetentionInDays: 14
